# dev local profile
spring:
  application:
    name: payment-service
  config:
    activate:
      on-profile: ${SPRING_PROFILES_ACTIVE:local}
  docker:
    compose:
      enabled: false
  logging:
    level:
      .web: DEBUG
      com.rj.payment_service: DEBUG
  jackson:
    default-property-inclusion: non_null

server:
  port: 8010
  error:
    include-message: always
    include-binding-errors: always

stripe:
  secret:
    key: ${STRIPE_SECRET_KEY}
    publishable: ${STRIPE_PUBLISHABLE_KEY}
---
# dev container profile
spring:
  application:
    name: payment-service
  config:
    activate:
      on-profile: ${SPRING_PROFILES_ACTIVE:dev}
  docker:
    compose:
      enabled: false
  logging:
    level:
      .web: DEBUG
      com.rj.payment_service: DEBUG
  jackson:
    default-property-inclusion: non_null

server:
  port: 8010
  error:
    include-message: always
    include-binding-errors: always

stripe:
  secret:
    key: ${STRIPE_SECRET_KEY}
    publishable: ${STRIPE_PUBLISHABLE_KEY}